Table admin {
  id_admin int [pk, increment]
  username varchar
  password varchar
  nama_admin varchar
}

Table kategori {
  id_kategori int [pk, increment]
  nama_kategori varchar
}

Table buku {
  id_buku int [pk, increment]
  id_admin int [ref: > admin.id_admin]
  id_kategori int [ref: > kategori.id_kategori]
  judul_buku varchar
  penulis varchar
  penerbit varchar
  tahun_terbit int
  jumlah_buku int
}

Table peminjaman {
  id_peminjaman int [pk, increment]
  id_buku int [ref: > buku.id_buku]
  tanggal_pinjam date
  tanggal_kembali date
  status varchar
}